name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-test
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - uses: volta-cli/action@v1
      - run: volta pin yarn
      - run: yarn install --pure-lockfile
      - run: yarn build
      - run: yarn test
        env:
          CI: true

  lint:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-lint
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - uses: volta-cli/action@v1
      - run: volta pin yarn
      - run: yarn install --pure-lockfile
      - run: yarn build
      - run: yarn lint
        env:
          CI: true

  publish:
    runs-on: ubuntu-latest
    needs: [lint, test]
    concurrency:
      group: ${{ github.ref }}-publish
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.7.0'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - uses: volta-cli/action@v1
      - run: volta pin yarn
      - run: yarn install --pure-lockfile
      - run: yarn build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}
