name: Node.js CI

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.7.0'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - uses: volta-cli/action@v1
      - run: volta pin yarn
      - run: yarn install --pure-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - run: yarn build
      - run: yarn test
        env:
          CI: true

  lint:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.7.0'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - uses: volta-cli/action@v1
      - run: volta pin yarn
      - run: yarn install --pure-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - run: yarn build
      - run: yarn lint
        env:
          CI: true

  build-and-push:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    needs:
      - test
      - lint
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Build container image
        run: |
          docker build -t registry.digitalocean.com/workers/bugbounty-programs-fetcher:$(echo $GITHUB_SHA | head -c7) \
            --build-arg npmtoken='${{secrets.NPM_AUTH_TOKEN}}' \
            .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DOCTL_TOKEN }}

      - name: Login to registry
        run: doctl registry login

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save elassandra

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/workers/bugbounty-programs-fetcher:$(echo $GITHUB_SHA | head -c7)

  deploy-prod:
    needs:
      - build-and-push
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DOCTL_TOKEN }}

      - name: Login to registry
        run: doctl registry login

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save general-purpose-cluster

      - name: Helm upgrade prod
        run: helm upgrade bugbounty-programs-fetcher ./bugbounty-programs-fetcher-chart --values ./bugbounty-programs-fetcher-chart/values.prod.yaml --set tag=$(echo $GITHUB_SHA | head -c7) --install

      - name: Cleanup deployment
        if: ${{ cancelled() }}
        run: helm rollback bugbounty-programs-fetcher
